### ISSUE TITLE
default fimware inching mode

### ISSUE THREAD

**Issue by Daviddevits** [nickdeacon/PIR-Lighting-controller#1]
Hi, nice work with programming the STM32f030C6T6 on the 4chpror2.
This does not really belong here but i do not now wher else i could contact you.
I need the default firmware with a lowest inching mode of 250ms (where the default firmware minimum is 1000ms)
Would that be possible? I do not have a STM32F0308-DISCO but do have a usb to serial cable.

**Comment by nickdeacon** [comment]
Hello Daviddevits, my modified firmware is designed to give much longer switching delays, so that it turns lights on for prolonged periods when a signal from a pir sensor is received. It is also designed to work with the RF signal from Sonoff sensors, so it might not work with other sensors. Having said that, if you want shorter switching periods of 250ms, then you could simply modify the TICKS_PER_SECOND constant to alter the timing base.
For programming the STM32, you need the ST-Link programmer, and you can either get a dedicated usb device or use the st-link on a STM32 development board as I did.

**Comment by Daviddevits** [comment]
Ok i got a STM32F0308-DISCO, and can connect. im completely new to st link do u have any hints on how i backup the existing firmware in case imake mistakes? just display the memory from 0x08000000 to 0x08008000 and use the save the displayed content to binary file option?

**Comment by nickdeacon** [comment]
Yes that is correct.
