### ISSUE TITLE
Triple click for RF learning

### ISSUE THREAD

**Issue by begicj** [nickdeacon/PIR-Lighting-controller#2]
Hi, I just tried the firmware and everything is ok. I wonder if it is possible to use a triple click for RF programming instead of a double click? 
Thanks in advance

**Comment by nickdeacon** [comment]
Yes you should be able to achieve this. The code is contained in button.c and basically when it detects a button down is sets a timeout for dblClickTimeout and when the button is released it sets dblClickState to 1. if the button is again pressed within timeout period and dblClickState is 1, then this is considered a double click. You could introduce a counter so that the double click is only activated if that counter reaches 3 by the time the dblClickTimout expires.
