### ISSUE TITLE
Got the schematic anywhere?

### ISSUE THREAD

**Issue by RoganDawes** [nickdeacon/PIR-Lighting-controller#3]
Hi,

I'm looking at writing my own firmware for the STM32 part in the 4CH Pro, but it seems like the published schematic diagrams have fallen off the internet. Even the wayback machine has not got copies of the Itead wiki, before they rearranged it. Do you perhaps have a copy stashed away?

I'm contemplating making a 433MHz KeeLoq receiver, with 4 output relays. Ideally, I'd like to repurpose some of the button or relay signals to allow a more full-featured communication between the ESP8285 and the STM32, e.g. via UART or I2C, rather than simple binary lines.

**Comment by nickdeacon** [comment]
Hi
Unfortunately I didn’t keep a copy of the schematic.

I have done some more work on this, and now have a controller for my outside lights, which I can control remotely via tcp on my local network. It is relatively easy to connect the TX/RX lines from the esp8285 to the stm32, so that commands can be sent in both directions. I have rewritten the firmware in the esp8285, it has a simple webserver running to allow delays and light-levels to be set and to manually switch the 4 channels between on, off or PIR states. It also allows tcp data to be sent and received so that I also have a small stm32 based controller with lcd touch screen to do the same control functions.

From my source code I could tell you what i/o pins are connected to the buttons and relays.



From: RoganDawes ***@***.***>
Sent: 01 June 2021 12:13
To: nickdeacon/PIR-Lighting-controller ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nickdeacon/PIR-Lighting-controller] Got the schematic anywhere? (#3)


Hi,

I'm looking at writing my own firmware for the STM32 part in the 4CH Pro, but it seems like the published schematic diagrams have fallen off the internet. Even the wayback machine has not got copies of the Itead wiki, before they rearranged it. Do you perhaps have a copy stashed away?

I'm contemplating making a 433MHz KeeLoq receiver, with 4 output relays. Ideally, I'd like to repurpose some of the button or relay signals to allow a more full-featured communication between the ESP8285 and the STM32, e.g. via UART or I2C, rather than simple binary lines.

**Comment by RoganDawes** [comment]
Thanks for responding, Nick. I'll keep looking, I guess.
